include: package:very_good_analysis/analysis_options.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    invalid_annotation_target: ignore
    todo: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated/**"
    - "**/l10n/**"

linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
    avoid_print: true
    prefer_const_constructors: false
    prefer_const_constructors_in_immutables: false
    prefer_const_literals_to_create_immutables: false
    prefer_final_locals: false
    prefer_single_quotes: true
    require_trailing_commas: false
    unawaited_futures: true
    use_super_parameters: true
    always_use_package_imports: false
    only_throw_errors: false
    cascade_invocations: false
    avoid_redundant_argument_values: false
    avoid_escaping_inner_quotes: false
